version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cointrackr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cointrackr
      DJANGO_DEBUG: "True"
      SECRET_KEY: dev-secret-change-me
      ALLOWED_HOSTS: 127.0.0.1,localhost
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      ACCESS_TOKEN_LIFETIME_MIN: 30
      REFRESH_TOKEN_LIFETIME_DAYS: 7
      COINGECKO_API_BASE: https://api.coingecko.com/api/v3
      COINGECKO_API_KEY: ""
      COINGECKO_CACHE_TTL_SECONDS: 300
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

