# Generated by Django 5.2.7 on 2025-10-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_id', models.CharField(max_length=128, unique=True)),
                ('symbol', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('last_price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='coins.coin')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('coin', 'date')},
            },
        ),
    ]
