# Generated by Django 5.2.7 on 2025-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['symbol'], name='coins_coin_symbol_218346_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['last_updated_at'], name='coins_coin_last_up_148898_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['coin', 'date'], name='coins_price_coin_id_4dbb2b_idx'),
        ),
    ]
