# Generated by Django 5.2.7 on 2025-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coin_coins_coin_symbol_218346_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='last_pct_change_24h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='last_volume_24h_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
    ]
